### PR TITLE
Fix tcache bin stack alignment.

### LINKED ISSUE #1606: test/unit/binshard segfaults since "Redesign the cache bin metadata"
Our CI discovered and I have reproduced locally, that since commit 7599c82d48ffaa07ce934320f7256b56b200dace the `test/unit/binshard` test segfaults on both ppc64 and ppc64le arches. Full backtrace is below
````
Core was generated by `test/unit/binshard /opt2/src/jemalloc/ /opt2/src/jemalloc/ '.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000000100454dc in extent_base_get (extent=<optimized out>) at src/extent.c:703
703		*r_elm_a = rtree_leaf_elm_lookup(tsdn, &extents_rtree, rtree_ctx,
[Current thread is 1 (Thread 0x7fffa53ed8e0 (LWP 47726))]
(gdb) where
#0  0x00000000100454dc in extent_base_get (extent=<optimized out>) at src/extent.c:703
#1  extent_rtree_leaf_elms_lookup (tsdn=tsdn@entry=0x0, rtree_ctx=rtree_ctx@entry=0x7fffa53ec160, extent=extent@entry=0x1, dependent=dependent@entry=true, 
    init_missing=init_missing@entry=false, r_elm_a=r_elm_a@entry=0x7fffa53ec2e8, r_elm_b=r_elm_b@entry=0x7fffa53ec2e0) at src/extent.c:704
#2  0x00000000100468d0 in extent_deregister_impl (tsdn=tsdn@entry=0x0, extent=0x1, gdump=true) at src/extent.c:859
#3  0x000000001004e934 in extent_deregister (extent=<optimized out>, tsdn=0x0) at src/extent.c:1097
#4  extent_recycle_split (new_addr=0x7fffaa3c35c0, growing_retained=true, extent=<optimized out>, szind=9, slab=true, alignment=65536, pad=0, size=327680, extents=0x7fffaa205748, 
    rtree_ctx=0x7fffa53ec3b0, r_extent_hooks=0x7fffa53ec780, arena=0x7fffaa200d80, tsdn=0x0) at src/extent.c:1097
#5  extent_recycle (tsdn=tsdn@entry=0x0, arena=arena@entry=0x7fffaa200d80, r_extent_hooks=r_extent_hooks@entry=0x7fffa53ec780, extents=extents@entry=0x7fffaa205748, 
    new_addr=new_addr@entry=0x0, size=size@entry=327680, pad=pad@entry=0, alignment=alignment@entry=65536, slab=<optimized out>, slab@entry=true, szind=<optimized out>, szind@entry=9, 
    zero=<optimized out>, zero@entry=0x7fffa53ec789, commit=<optimized out>, commit@entry=0x7fffa53ec788, growing_retained=true) at src/extent.c:1148
#6  0x000000001004f990 in extent_alloc_retained (commit=0x7fffa53ec788, zero=0x7fffa53ec789, szind=9, slab=true, alignment=65536, pad=0, size=327680, new_addr=0x0, 
    r_extent_hooks=0x7fffa53ec780, arena=0x7fffaa200d80, tsdn=0x0) at src/extent.c:1471
#7  jet_extent_alloc_wrapper (tsdn=0x0, arena=0x7fffaa200d80, r_extent_hooks=0x7fffa53ec780, new_addr=0x0, size=327680, pad=0, alignment=65536, slab=<optimized out>, szind=<optimized out>, 
    zero=<optimized out>, commit=<optimized out>) at src/extent.c:1539
#8  0x0000000010017258 in arena_slab_alloc_hard (bin_info=<optimized out>, szind=9, r_extent_hooks=<optimized out>, arena=0x7fffaa200d80, tsdn=0x0) at src/arena.c:1217
#9  arena_slab_alloc (bin_info=<optimized out>, binshard=0, binind=9, arena=0x7fffaa200d80, tsdn=0x0) at src/arena.c:1247
#10 arena_bin_nonfull_slab_get (binshard=0, binind=9, bin=0x7fffaa211750, arena=0x7fffaa200d80, tsdn=0x0) at src/arena.c:1283
#11 arena_bin_malloc_hard (tsdn=tsdn@entry=0x0, arena=arena@entry=0x7fffaa200d80, bin=bin@entry=0x7fffaa211750, binind=binind@entry=9, binshard=binshard@entry=0) at src/arena.c:1319
#12 0x000000001001c820 in arena_malloc_small (zero=false, binind=9, arena=0x7fffaa200d80, tsdn=0x0) at src/arena.c:1475
#13 jet_arena_malloc_hard (tsdn=0x0, arena=0x7fffaa200d80, size=<optimized out>, ind=<optimized out>, zero=<optimized out>) at src/arena.c:1527
#14 0x0000000010008da4 in arena_malloc (slow_path=true, tcache=0x0, zero=<optimized out>, ind=<optimized out>, size=136, arena=<optimized out>, tsdn=0x0)
    at include/jemalloc/internal/arena_inlines_b.h:176
#15 iallocztm (slow_path=true, arena=<optimized out>, is_internal=true, tcache=0x0, zero=<optimized out>, ind=<optimized out>, size=136, tsdn=0x0)
    at include/jemalloc/internal/jemalloc_internal_inlines_c.h:53
#16 a0ialloc (size=size@entry=136, zero=zero@entry=false, is_internal=is_internal@entry=true) at src/jemalloc.c:240
#17 0x0000000010009688 in jet_a0malloc (size=136) at src/jemalloc.c:452
#18 jet_arena_tdata_get_hard (tsd=0x7fffa53ee050, ind=<optimized out>) at src/jemalloc.c:452
#19 0x000000001001cf38 in arena_tdata_get (refresh_if_missing=true, ind=<optimized out>, tsd=0x7fffa53ee050) at include/jemalloc/internal/jemalloc_internal_inlines_a.h:73
#20 decay_ticker_get (ind=<optimized out>, tsd=0x7fffa53ee050) at include/jemalloc/internal/jemalloc_internal_inlines_a.h:104
#21 arena_decay_ticks (nticks=1, arena=0x7fffa3400c80, tsdn=0x7fffa53ee050) at include/jemalloc/internal/arena_inlines_b.h:121
#22 arena_decay_tick (arena=0x7fffa3400c80, tsdn=0x7fffa53ee050) at include/jemalloc/internal/arena_inlines_b.h:135
#23 arena_malloc_small (zero=<optimized out>, binind=<optimized out>, arena=0x7fffa3400c80, tsdn=0x7fffa53ee050) at src/arena.c:1510
#24 jet_arena_malloc_hard (tsdn=0x7fffa53ee050, arena=0x7fffa3400c80, size=<optimized out>, ind=<optimized out>, zero=<optimized out>) at src/arena.c:1527
#25 0x0000000010010474 in arena_malloc (slow_path=<optimized out>, tcache=<optimized out>, zero=<optimized out>, ind=<optimized out>, size=<optimized out>, arena=<optimized out>, 
    tsdn=<optimized out>) at include/jemalloc/internal/arena_inlines_b.h:176
#26 iallocztm (slow_path=<optimized out>, arena=<optimized out>, is_internal=<optimized out>, tcache=<optimized out>, zero=<optimized out>, ind=<optimized out>, size=<optimized out>, 
    tsdn=<optimized out>) at include/jemalloc/internal/jemalloc_internal_inlines_c.h:53
#27 imalloc_no_sample (ind=0, usize=8, size=1, tsd=0x7fffa53ee050, dopts=<synthetic pointer>, sopts=<synthetic pointer>) at src/jemalloc.c:1949
#28 imalloc_body (tsd=0x7fffa53ee050, dopts=<synthetic pointer>, sopts=<synthetic pointer>) at src/jemalloc.c:2149
#29 imalloc (dopts=<synthetic pointer>, sopts=<synthetic pointer>) at src/jemalloc.c:2258
#30 jet_mallocx (size=1, flags=<optimized out>) at src/jemalloc.c:3136
#31 0x0000000010002030 in thd_producer (varg=0x7fffc39e5d20) at test/unit/binshard.c:19
#32 0x00007fffaa7c8c10 in start_thread (arg=0x7fffa53ed8e0) at pthread_create.c:486
#33 0x00007fffaa6dd8a8 in clone () at ../sysdeps/unix/sysv/linux/powerpc/powerpc64/clone.S:82
````

### PR DESCRIPTION
**Pull request by interwq**
Set the proper alignment when allocating space for the tcache bin stack.

The bug was Introduced in 7599c82. 

Resolves #1606

### CODE REVIEW

**Comment by interwq** [comment]
The bug was reproducible with 64k page size. I'll add `--with-lg-page=16` to our CI in a later PR.

File: src/tcache.c [hunk 1]
```diff
@@ -492,20 +492,23 @@ tcache_init(tsd_t *tsd, tcache_t *tcache, void *avail_stack) {
 
 static size_t
 tcache_bin_stack_alignment (size_t size) {
+	if (LG_SIZEOF_PTR < 3 || size < PAGE) {
```
Comment (davidtgoldblatt) [inline src/tcache.c]: Shouldn't this be:
```
size_t correctness_alignment = pow2_ceil_zu(size);
size_t performance_alignment = CACHELINE; // Or page, whatever granularity we pick.
return max(correctness_alignment, performance_alignment);  
}
```
?
I don't follow why pointer size matters here at all.

Comment (interwq) [reply src/tcache.c]: Ah the pointer size is because, the alignment is to avoid overflowing the "half" pointers in the cache bin metadata. Those are 32bits pointers so no overflow concerns there.

Comment (interwq) [reply src/tcache.c]: Added some comments for the 32bit case.

**Comment by interwq** [comment]
Only comments were updated. Merging.
